name: PHP CI

on:
  - push
  - pull_request

jobs:
  build:
    name: Run
    runs-on: ${{ matrix.operating-systems }}
    strategy:
      matrix:
        operating-systems: [macos-latest, ubuntu-latest]
        php-versions: ['8.1', '8.2']

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install
        run: make install

      - name: Validate
        run: make validate

      - name: Run linter
        run: make lint
